### ISSUE TITLE
ValueError: AdamW: some parameters appear in more than one parameter group

### ISSUE THREAD

**Issue by lc03lc** [zkyseu/O2SFormer#16]
I experienced the following error while deploying the code to the CULane dataset:
Traceback (most recent call last):
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/torch/optim/adamw.py", line 92, in __init__
    super(AdamW, self).__init__(params, defaults)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/torch/optim/optimizer.py", line 66, in __init__
    self.add_param_group(param_group)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/torch/optim/optimizer.py", line 346, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lc03lc/o2sformer/train_net.py", line 248, in <module>
    main()
  File "/home/lc03lc/o2sformer/train_net.py", line 244, in main
    meta=meta)
  File "/home/lc03lc/o2sformer/dnlane/apis/train.py", line 172, in train_detector
    optimizer = build_optimizer(model, cfg.optimizer)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/mmdet/core/optimizers/builder.py", line 32, in build_optimizer
    optimizer = optim_constructor(model)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/mmcv/runner/optimizer/default_constructor.py", line 258, in __call__
    return build_from_cfg(optimizer_cfg, OPTIMIZERS)
  File "/home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: AdamW: some parameters appear in more than one parameter group
How do I solve this problem?

**Comment by zkyseu** [comment]
@lc03lc Hi, this problem is caused by MMCV. You can solve this problem by running the following code

step 1:
`
vim /home/lc03lc/.conda/envs/lane/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py
` 

step 2: Replace the false code following this [PR](https://github.com/open-mmlab/mmcv/pull/2444/commits/4290c68f653f63e96f022f330ceb71b578ee602d).
