### ISSUE TITLE
训练的代码问题

### ISSUE THREAD

**Issue by HuangZeLinCute** [zkyseu/O2SFormer#24]
训练的时候我遇到了这个问题
The value is the same before and after calling `init_weights` of DNLATR

Traceback (most recent call last):
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 57, in __init__
    self.parser_datalist()
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 65, in parser_datalist
    infos = self.load_annotation(line.split())
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 92, in load_annotation
    with open(anno_path, 'r') as anno_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/CULane/driver_182_30frame/06011143_0165.MP4/00000.lines.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHubProject\O2SFormer-main\train_net.py", line 248, in <module>
    main()
  File "D:\GitHubProject\O2SFormer-main\train_net.py", line 222, in main
    datasets = [build_dataset(cfg.data.train)]
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmdet\datasets\builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CULaneDataset: [Errno 2] No such file or directory: 'data/CULane/driver_182_30frame/06011143_0165.MP4/00000.lines.txt
代码错误是culane_dataset.py的：
        anno_path = img_path[:-3] + 'lines.txt'  # remove sufix jpg and add lines.txt
        with open(anno_path, 'r') as anno_file:
            data = [list(map(float, line.split())) for line in anno_file.readlines()]
        lanes = [[(lane[i], lane[i + 1]) for i in range(0, len(lane), 2) if lane[i] >= 0 and lane[i + 1] >= 0]
                 for lane in data]
        lanes = [list(set(lane)) for lane in lanes]  # remove duplicated points
        lanes = [lane for lane in lanes if len(lane) > 3]  # remove lanes with less than 2 points
这里是否是写错了？
期待你回复

**Comment by zkyredstart** [comment]
应该是数据集路径错了，可以用一些绝对路径，需要保证driver_182_30frame/的根目录是绝对路径

**Comment by HuangZeLinCute** [comment]
我修改了绝对路径之后还是这个错误。Traceback (most recent call last):
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 57, in __init__
    self.parser_datalist()
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 65, in parser_datalist
    infos = self.load_annotation(line.split())
  File "D:\GitHubProject\O2SFormer-main\dnlane\datasets\culane_dataset.py", line 92, in load_annotation
    with open(anno_path, 'r') as anno_file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/GitHubProject/O2SFormer-main/data/CULane\\driver_182_30frame/06011143_0165.MP4/00000.lines.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHubProject\O2SFormer-main\train_net.py", line 248, in <module>
    main()
  File "D:\GitHubProject\O2SFormer-main\train_net.py", line 222, in main
    datasets = [build_dataset(cfg.data.train)]
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmdet\datasets\builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\14181\anaconda3\envs\O2S\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CULaneDataset: [Errno 2] No such file or directory: 'D:/GitHubProject/O2SFormer-main/data/CULane\\driver_182_30frame/06011143_0165.MP4/00000.lines.txt'
anno_path = img_path[:-3] + 'lines.txt' # remove sufix jpg and add lines.txt
可以告诉我这条代码要讲图片的后缀转换为txt吗？

**Comment by zkyredstart** [comment]
请确认一下main/data/CULane\driver_182_30frame/06011143_0165.MP4/00000.lines.txt'这个路径是否真的存在，其次路径里一般都是“/”作为分隔符，linux 里一般不用"\"哈，这个问题其实就是数据集路径或者格式问题，可以仔细检查一下哈

**Comment by HuangZeLinCute** [comment]
如果我是win系统的话可以跑的起来这个程序吗？

**Comment by zkyredstart** [comment]
@HuangZeLinCute 我们的代码基于MMdetection，MM detection支持windows，我们程序就可以跑起来。
