### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by hard-workingXu** [zkyseu/O2SFormer#25]
Hello, I ran into this problem in training, it looks like I can't convert the floating point NaN (null) to an integer, is this problem the data itself? Or is it something else? The following are the specific error reports：
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/lx/anaconda3/envs/0s2/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py:21: RuntimeWarning: invalid value encountered in long_scalars
  size / self.samples_per_gpu)) * self.samples_per_gpu
Traceback (most recent call last):
  File "train_net.py", line 248, in <module>
    main()
  File "train_net.py", line 244, in main
    meta=meta)
  File "/home/lx/桌面/O2SFormer-main/dnlane/apis/train.py", line 154, in train_detector
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/home/lx/桌面/O2SFormer-main/dnlane/apis/train.py", line 154, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/home/lx/anaconda3/envs/0s2/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 181, in build_dataloader
    samples_per_gpu) if shuffle else None
  File "/home/lx/anaconda3/envs/0s2/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 21, in __init__
    size / self.samples_per_gpu)) * self.samples_per_gpu
ValueError: cannot convert float NaN to integer

**Comment by zkyredstart** [comment]
Hi, what is the version of your mmdet and mmcv?
